# Generated by Django 6.0.2 on 2026-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeobject',
            name='infrastructure_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
