# Generated by Django 6.0.2 on 2026-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placeobject_infrastructure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeobject',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
