# Generated by Django 6.0.2 on 2026-02-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placeobject_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='placeobject',
            constraint=models.UniqueConstraint(fields=('title', 'address'), name='unique_place_title_address'),
        ),
    ]
