# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


def seed_places_and_reviews(apps, schema_editor):
    PlaceObject = apps.get_model("core", "PlaceObject")
    PlaceReview = apps.get_model("core", "PlaceReview")

    place1, _ = PlaceObject.objects.get_or_create(
        title="КАРО 11 Октябрь",
        address="ул. Новый Арбат, 24",
        defaults={
            "description": "Кинотеатр «КАРО 11 Октябрь» — это большой и красивый зал с большим экраном и сценой. Здесь часто проходят закрытые показы кинофильмов вместе с актерами, режиссерами и участниками съемок.",
            "infrastructure_type": "Кинотеатр",
            "schedule": "ежедневно, 10:00-02:00",
            "metros": ["Смоленская", "Смоленская", "Арбатская"],
            "image_url": "https://avatars.mds.yandex.net/get-altay/1881734/2a0000016b31d4a3311953c7416353d0c893/XXL",
            "map_image_url": "https://i.imgur.com/kM8v7vJ.png",
            "sign_language": True,
            "subtitles": True,
            "ramps": True,
            "braille": True,
        },
    )

    place2, _ = PlaceObject.objects.get_or_create(
        title="Театр Мимики и Жеста",
        address="Измайловский бул., 41",
        defaults={
            "description": "Театр с программами для глухих и слабослышащих посетителей, удобной навигацией и доступной средой.",
            "infrastructure_type": "Театр",
            "schedule": "ежедневно, 10:00-21:00",
            "metros": ["Первомайская"],
            "image_url": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/34/40/1f/caption.jpg?w=1200&h=-1&s=1",
            "map_image_url": "https://i.imgur.com/kM8v7vJ.png",
            "sign_language": True,
            "subtitles": True,
            "ramps": True,
            "braille": False,
        },
    )

    if not PlaceReview.objects.filter(place=place1).exists():
        PlaceReview.objects.create(
            place=place1,
            author_name="User",
            text="Со всей семьей смотрели фильм, топчик, советую туда сходить, т.к. есть субтитры!",
        )
        PlaceReview.objects.create(
            place=place1,
            author_name="User1",
            text="Хорошее место",
        )

    if not PlaceReview.objects.filter(place=place2).exists():
        PlaceReview.objects.create(
            place=place2,
            author_name="Anna",
            text="Очень комфортная среда и вежливый персонал.",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_placeobject_unique_place_title_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeobject",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="placeobject",
            name="map_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="placeobject",
            name="metros",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="placeobject",
            name="schedule",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_name", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("place", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="reviews", to="core.placeobject")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(seed_places_and_reviews, migrations.RunPython.noop),
    ]
