# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_placeobject_details_and_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeobject",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="places/"),
        ),
    ]
