# Generated by Django 6.0.2 on 2026-02-21 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_placeobject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
