# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
