# Generated by Django 6.0.2 on 2026-02-21 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('infrastructure_type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('schedule', models.CharField(blank=True, max_length=120)),
                ('metros', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('map_image_url', models.URLField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='places/')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('sign_language', models.BooleanField(default=False)),
                ('subtitles', models.BooleanField(default=False)),
                ('ramps', models.BooleanField(default=False)),
                ('braille', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'address'), name='unique_place_title_address')],
            },
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.placeobject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
